---
language: python
dist: xenial
cache: pip
sudo: false

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - libffi-dev
    - libpcre3-dev
    - tox

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6.5
    - env: TOXENV=py27-static
      python: 2.7.15
    - env: TOXENV=py27-dynamic
      python: 2.7.15
    - env: TOXENV=pypy-static
      python: pypy2.7-5.10.0
    - env: TOXENV=pypy-dynamic
      python: pypy2.7-5.10.0
    - env: TOXENV=py35-static
      python: 3.5
    - env: TOXENV=py35-dynamic
      python: 3.5
    - env: TOXENV=pypy3-static
      python: pypy3.5
    - env: TOXENV=pypy3-dynamic
      python: pypy3.5
    - env: TOXENV=py36-static
      python: 3.6.5
    - env: TOXENV=py36-dynamic
      python: 3.6.5
    - env: TOXENV=py37-static
      python: 3.7.1
    - env: TOXENV=py37-dynamic
      python: 3.7.1

script: tox -- $(git ls-files '*.py')
