# Copyright (c) 2020 Robin Jarry
# SPDX-License-Identifier: MIT
---
name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade tox
      - run: python -m tox -e lint

  check-commits:
    if: ${{ github.event.pull_request.commits }}
    runs-on: ubuntu-latest
    env:
      LYPY_COMMIT_RANGE: "HEAD~${{ github.event.pull_request.commits }}.."
    steps:
      - run: sudo apt-get install git make
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - run: make check-commits

  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - python: "3.9"
            toxenv: py39
          - python: "3.10"
            toxenv: py310
          - python: "3.11"
            toxenv: py311
          - python: "3.12"
            toxenv: py312
          - python: "3.13"
            toxenv: py313
          - python: pypy3.9
            toxenv: pypy3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade tox
      - run: python -m tox -e ${{ matrix.toxenv }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade tox
      - run: python -m tox -e coverage
      - uses: codecov/codecov-action@v3

  deploy:
    needs: [lint, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.03
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade pep517 twine
      - run: python -m pep517.build --out-dir dist/ --source .
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}
