# Copyright (c) 2020 Robin Jarry
# SPDX-License-Identifier: MIT
---
name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.x
            toxenv: lint
          - python: 3.5
            toxenv: py35
          - python: 3.6
            toxenv: py36
          - python: 3.7
            toxenv: py37
          - python: 3.8
            toxenv: py38
          - python: pypy3
            toxenv: pypy3
          - python: 3.x
            toxenv: py3-master
          - python: 3.x
            toxenv: py3-devel
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade tox
      - run: python -m tox -e ${{ matrix.toxenv }}
